# Generated by Django 5.1.3 on 2024-12-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ref_key', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
    ]
